export const SET_SEARCHED_ITEMS = 'SET_SEARCHED_ITEMS';

export const RECORD_TRACKLOG_POINT = 'RECORD_TRACKLOG_POINT'

export const SET_CURRENT_TRACKLOG = 'SET_CURRENT_TRACKLOG'

export const CLEAR_CURRENT_TRACKLOG = 'CLEAR_CURRENT_TRACKLOG'

export const SET_NEW_TRACKLOG_POINT = 'SET_NEW_TRACKLOG_POINT';

export const ADD_ITEM = 'ADD_ITEM';